version: '3.9'
services:
  db:
    image: postgres:16
    container_name: my-postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - db:/var/lib/postgresql/data

  server:
    build: ./server
    container_name: my-server
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - ./.env 
    depends_on:
      - db
    volumes:
      - ./init-db.sql:/server/init-db.sql

  client:
    build: ./client
    container_name: my-client
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - server

volumes:
  db:

